### ISSUE TITLE
PR App Previews

### ISSUE THREAD

**Issue by iRoachie** [react-native-training/react-native-elements#1022]
Generate a preview version of the changes in PR to verify if it breaks the RNE app

**Comment by xavier-villelegier** [comment]
(Cf [`react-navigation` PRs](https://github.com/react-navigation/react-navigation/pulls), WIP on [these PRs](https://github.com/xavier-villelegier/react-native-elements/pulls))

**Comment by xavier-villelegier** [comment]
Merged and live on `next`. Still need to enhance this by editing the comment instead of commenting. (I'll work on that this week-end, should be ready for `v1.0.0-beta4` release)


TD;DR
@Monte9 @iRoachie 
We also need to find a solution for external PRs. The fact that the example app is in another repo and people cannot update it by adding example of what they've done in the PR makes the system a bit less effective. If there are breaking changes, then the app will be broken, people should be able to update it and add some examples (and we should see them on the deployed app).

I think we'll need to find another way than the submodule to have live-development + example app in the RNE repo. In this case, people will be able to add examples in their PRs, and we'll see them in the automatically deployed app 🎉
