### ISSUE TITLE
Button: Inconsistency on button's disabled style

### ISSUE THREAD

**Issue by mhsekhavat** [react-native-training/react-native-elements#1063]
`Button` component renders a `<ViewComponent/>` and a `<Text/>` inside it. For a `Button` with `disabled` attribute, `styles.disabled` overrides `buttonStyle` in styles of `ViewComponent` but `styles.disabledTitle` does not override `titleStyle` in styles of `Text`. 

Commit https://github.com/react-native-training/react-native-elements/commit/5af9b15a16935440aa25db6a03d53a80e5be197a has moved `buttonStyle` after `styles.disabled` but `titleStyle` is still before `styles.disabledTitle`:

https://github.com/react-native-training/react-native-elements/blob/1c1561c00cdfeb6e554388707bc1c44e6097b646/src/buttons/Button.js#L72-L74

https://github.com/react-native-training/react-native-elements/blob/1c1561c00cdfeb6e554388707bc1c44e6097b646/src/buttons/Button.js#L100-L101

This causes inconsistency in a usage like this:
```jsx
<Button buttonStyle={{backgroundColor:'black', color:'white'}} disabled={true} />
```
This component will have black background but gray text color which is neither user's style (color != white) nor default disabled style (backgroundColor != #D1D5D8)

**Comment by xavier-villelegier** [comment]
@mhsekhavat Aaah yea I fixed if for the `buttonStyle` but I missed the `titleStyle`, my bad ! Feel free to open a PR if you have time, in any case this should be fixed in the next release

**Comment by ganes1410** [comment]
@xavier-villelegier can i do this ?

**Comment by xavier-villelegier** [comment]
@ganes1410 Sure dude

**Comment by xavier-villelegier** [comment]
@mhsekhavat @ganes1410 
I've been thinking about this, and here is what I think:

First, @mhsekhavat `buttonStyle={{backgroundColor:'black', color:'white'}}` won't work to set the white color on the title, you have to use `titleStyle`

To my mind, the styles should be overridden in this order:
1) Default style
2) User style
3) Default disabled style
4) User disabled style

Imagine you just want to customize the `backgroundColor`, as you did.
```
<Button buttonStyle={{backgroundColor:'black', color:'white'}} />
```

Currently, if you add `disabled` to your `Button`, the appearance won't change, because `buttonStyle` __overrides__ the default disable style. You should be able to customize the button, but still have the default disabled style. And finally, if you wan't a custom disabled style, then you provide a `disabledStyle`, but you shouldn't be forced to, just because you used the `disabled` props

@ganes1410 I've reviewed indicating the order that it should be

**Comment by mhsekhavat** [comment]
@xavier-villelegier Thanks for your point! I have over-simplified my example to explain the concept.

> Default style
> User style
> Default disabled style
> User disabled style

I pretty much agree with this order.

**Comment by xavier-villelegier** [comment]
Live in `v1.0.0-beta5` on npm, thanks again @mhsekhavat ! 💯
