### ISSUE TITLE
Static typing with flow in favour of propTypes

### ISSUE THREAD

**Issue by giacomocerquone** [react-native-training/react-native-elements#1067]
Trying to split this discussion born in #960 in order to resolve that issue and implement type checking in a static way instead of using propTypes.

As of now using flow, for example, would let us resolve that problem and remove type checking in production build where it shouldn't be.
We pointed out that Dan Abramov also stripped out proptypes in production from its CRA for various reasons and it seems to me the way to go. https://github.com/facebook/create-react-app/issues/209

It should also make smaller the output of the react native elements build.

**Comment by iRoachie** [comment]
I think our use case for prop-types maybe slightly different than a repo like create-react-app. UI libraries are presentational components, which means that if we allow incorrect props, the it could break the UI. 

Last year we added typescript definitions, largely because I was using react-native with typescript. However this was a good move for us, since VSCode's intellisense is also powered by typescript definitions. By having this users were hinted at which props are valid. Implementing this required no changes to the actual src.  **Best part about this is that it provides benefits for both those who don't use static typing and those using typescript.** 

Adding static typing provides another thing that user's need to keep update with and contribute to when contributing. One of the reason we have so much growth is because (people love RNE!) and because we make it really easy to contribute. I thinking adding static typing would create a barrier to entry. We have a very small core team of 4 members, so users being able to "fix their own issues" and implement their own enhancements is a huge thing.

So although I think it'd be great to have static typing in source files - we have to take note the majority of users aren't using Typescript or Flow, and using `prop-types` is the only method we have for validating inputs for that user set.

**Comment by cglacet** [comment]
I guess someone must have defined these types already, are you aware of a side project that only aims at maintaining static types for props?
