### ISSUE TITLE
 "fontFamily 'Ionicons' is not a system font and has not been loaded through Expo.Font.loadAsync"

### ISSUE THREAD

**Issue by pleopardi** [react-native-training/react-native-elements#1134]
### Description

I'm trying to use the CheckBox component within an Expo project but I get the error in the title.

This is the code I'm using:

`<CheckBox
      checked={checked}
      checkedIcon="ios-checkbox"
      checkedColor={DEEP_BLUE}
      containerStyle={containerStyle}
      iconType="ionicon"
      onPress={onPress}
      textStyle={textStyle}
      title={title}
      uncheckedColor={DEEP_BLUE}
      uncheckedIcon="ios-square-outline"
    />`

I'm already preloading the Ionicons imported from @ expo/vector-icons and I also tried to preload Ionicons.ttf from react-native-vector-icons/Fonts but I still get the error.

I'm using react-native-elements 0.18.5.

**Comment by xavier-villelegier** [comment]
@pleopardi Mmmh it works out of the box in [this snack](https://snack.expo.io/BJDDK8n2z) without preloading anything.

Make sure you read https://github.com/react-native-training/react-native-elements/issues/620#issuecomment-355530210

**Comment by pleopardi** [comment]
Thanks Xavier. I read your comment yesterday and tried your solution with no luck.

I'll try again after updating the dependencies, starting from expo and react-native-elements. Maybe it's some kind of legacy bug easily solved with an update.

**Comment by xavier-villelegier** [comment]
@pleopardi Could you try with `v1.0.0-beta4` ? `npm i -S react-native-elements@beta`, remember to clean install your modules (`rm -rf node_modules yarn.lock package-lock.json && yarn`)

**Comment by pleopardi** [comment]
I tried with v1.0.0-beta4 but still have the same problem!

**Comment by pleopardi** [comment]
OK, I tried with a new Expo project from scratch and everything works just fine, without precaching by the way. 
So the problem it's almost certainly related to the other Expo project, altough I don't know yet what causes it.

Anyway, problem solved! Thanks again for your help Xavier.

**Comment by xavier-villelegier** [comment]
Glad it doesn't come from RNE ! Feel free to post the solution if you find out.

**Comment by pinchez254** [comment]
having same error while using check box from native base fontFamily 'Ionicons' is not a system font and has not been loaded through Expo.Font.loadAsync.

**Comment by rmoni3000** [comment]
I started having this problem recently too, I suspect it might be some dependency but couldn't find which one.
**The problem is that this error is intermittent**

1. I'm using expo, and started a clean project with "expo init" at SDK 30
2. Added the following dependencies:

- axios
- babel-preset-env
- babel-preset-expo
- cnpj
- cpf
- expo
- intl
- lodash
- moment
- native-base
- numeral
- pouchdb
- pouchdb-adapter-asyncstorage
- pouchdb-find
- querystring
- react
- react-native
- react-native-modal-dropdown
- react-native-modalbox
- react-navigation
- react-redux
- redux
- redux-form
- redux-multi
- redux-promise
- redux-thunk

3. It worked for me
4. I committed
5. Cloned on my coworker macbook, ran, it worked
6. Then he committed some dummy alteration
7. **I cloned again on my machine, suddenly stopped working giving this error.... :(**

**Comment by pinchez254** [comment]
the problem is with icons..always use vector icons with expo  ..either install them or use the ones that comes with expo like this

import React from 'react';
import { Ionicons } from '@expo/vector-icons';

export default class IconExample extends React.Component {
  render() {
    return (
      <Ionicons name="md-checkmark-circle" size={32} color="green" />
    );
  }
}

please do check https://docs.expo.io/versions/latest/guides/icons

**Comment by pinchez254** [comment]
https://docs.expo.io/versions/latest/guides/icons

**Comment by akshaykatale99** [comment]
Facing the same issue tried all workarounds but still facing error..
here is my code

import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { AppNavigator } from './appNavigation';
import { AppLoading } from 'expo';
import { Asset } from 'expo-asset';
import * as Font from 'expo-font';
import { Ionicons } from '@expo/vector-icons';

function cacheFonts(fonts) {
  return fonts.map(font => Font.loadAsync(font));
}

export default class App extends React.Component {

  state = {
    isReady: false,
  };

  async _loadAssetsAsync() {
    await Font.loadAsync(Ionicons.font);
  }

  render() {
    if (!this.state.isReady) {
      return (
        <AppLoading
          startAsync={this._loadAssetsAsync}
          onFinish={() => this.setState({ isReady: true })}
          onError={console.warn}
        />
      );
    }

    return (
      <View> <Ionicons name="md-checkmark-circle" size={32} color="green" /></View>
    );
  }
}

const AppNav = AppNavigator;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

**Comment by konuralpt** [comment]
this worked for me
```
rm -rf node_modules && yarn install
```
