### ISSUE TITLE
Weird behavior with `alignItems: 'center'` v1 ListItem

### ISSUE THREAD

**Issue by jason-cf** [react-native-training/react-native-elements#1142]
### Description

1. Explain what you did
_Followed example for ListItem, using 1.0.0-beta4, 'title' property doesn't appear to work._ 

2. What you expected to happen
_'title' field should show my text. I hard coded it to 'foobar'._

3. What actually happens
_list appears with just icons, but no title_

Also please include the version of `react-native-elements` that you are using.
_"react-native-elements": "^1.0.0-beta4",
"react": "^16.3.1",
"react-native": "^0.55.2",
iOS_

### Reproduction Steps and Sample Code

```
render() {
    const list = [
        {
          title: "Appointments",
          icon: 'av-timer'
        },
        {
          title: 'Trips',
          icon: 'flight-takeoff'
        },
      ];

    return (
      <View>
                  {
                    list.map((item, i) => (
                        <ListItem
                            key={i}
                            title="foobar"
                            leftIcon={{ name: item.icon }}
                        />
                    ))
                }
      </View>
    );
  }
}
```

**Comment by xavier-villelegier** [comment]
@jason-cf Adding `alignItems: 'center'` will cause children to take the minimum width and center themselves. The title is in a view with `flex: 1` style, and it seems like there are some conflicts between `flex: 1` child and `alignItems: 'center'` container.

Basically: you ask to your children to take the minimum width but the `flex: 1` tries to take maximum available width -> which is actually 0 because of the `alignItems: 'center'`.

You can easily test that by adding `contentContainerStyle={{ flex: 0 }}`, which makes the content container view take just the needed space (but still the minimum width because of `alignItems: 'center'`).
![image](https://user-images.githubusercontent.com/17592779/39296462-40a48f3a-4941-11e8-83da-6f78f738b99f.png)

You can also set a `width` to the container by adding `containerStyle={{ width: '100%' }}`
![image](https://user-images.githubusercontent.com/17592779/39296517-6ae3f0e2-4941-11e8-9016-26c9cf2f7733.png)


The easiest thing is still to let the `ListItem` in a view that doesn't have `alignItems: 'center'`.

**Comment by jason-cf** [comment]
@xavier-villelegier your suggestion for a workaround works for me, but I still think `flex: 1` and `alignItems: 'center'` should not cause the issue I encountered. I re-read the mozilla spec, and it doesn't say it'd cause elements to take a min width of 0. Take for example the same code, but instead of using `ListItem`, just simply use `<Text>` instead. Things display correctly, and the min width is the width of the text, not zero. 


```
const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.white,
  },
)}

   render() {
        const list = [
            {
            title: "Appointments",
            icon: 'av-timer'
            },
            {
            title: 'Trips',
            icon: 'flight-takeoff'
            },
        ];

        return (

            <View style={styles.container}>
                    {
                        list.map((item, i) => (
                            <Text style={{backgroundColor:'#fff'}}> foobar </Text>
                        ))
                    }
            </View>
        );
    }
```


I think most users would expect the text inside `ListItem` to have the same behavior as `<Text>`, but I guess it's okay if it doesn't for now. I'm glad you were able to help me moving forward again. Thanks for investigating this issue!

**Comment by xavier-villelegier** [comment]
The fact is that the `ListItem` cannot be as simple as a single `Text`, because of the number of features built-in, so the `Text` is wrapped many times before the `Text`. Here is more or less what is rendered by the `ListItem`:

```jsx
list.map((item) => (
  <View>
    <View style={{ flexDirection: 'row', alignItems: 'center'}}>
      <View style={{flex: 1, justifyContent: 'center'}}>
        <Text style={{backgroundColor:'#fff'}}> foobar </Text>
      </View>
    </View>
  </View>
))
```

And you can see that the behavior is the same as the `ListItem`, (the `Text` doesn't show up)
The weird thing is that if you just add `alignItems: center` to the outter `View`, it shows up as you expected. (cc @martinezguillaume, I think there is something to improve there)

But you're right, this shouldn't be this way, so I'll label this issue as a bug.

By the way, seeing these weird behaviors, I wouldn't assume that React Native is following exactly mozilla spec, there are many differences between platforms

**Comment by jason-cf** [comment]
@xavier-villelegier, I totally agree you expect react-native to be fully compliant to the mozilla spec. You reminded me that just recently when React 16.2 was introduced, I've actually been able to fix some strange layout issues by using `React fragments` instead of `<View>`. FYI, I use RN .55, and maybe I'm missing something, but I can't get the short-hand notation `<>` to work, but the long-hand `<React.Fragment></React.Fragment>` works for me.

**Comment by xavier-villelegier** [comment]
@jason-cf Oh okay nice ! Could you post your Fragment-solution ? I didn't have the occasion to use fragment yet, could be a good example !

**Comment by martinezguillaume** [comment]
@jason-cf I tried your example but it seems that it doesn't work that way. If you remove the Fragment from your code, it continues to work normally. I think that there is a thing that we miss in the ListItem component, I'll investigate later

ps: I still tried add Fragment to ListItem but it doesn't work 😢

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.
