### ISSUE TITLE
SearchBar onCancel does not work when ListHeaderComponent in FlatList

### ISSUE THREAD

**Issue by jfrolich** [react-native-training/react-native-elements#1147]
### Description

onCancel does not trigger when pressing cancel when a ListHeaderComponent in a FlatList

-- 
PS: A small bug, the cursor animates when focussing, and this should not happen on iOS
PPS: The touch target for the clear button is really small, so you often miss it

1.0.0-beta4

### Reproduction Steps and Sample Code

https://snack.expo.io/H1nxCdg6M

**Comment by xavier-villelegier** [comment]
@jfrolich This is not because of the SearchBar, but because of the FlatList. You need to add `keyboardShouldPersistTaps="handled"` to your FlatList props.

For the cursor animation, we're using `LayoutAnimation` (which animates basically everything). We will probably change that to use the `Animated` API later.
