### ISSUE TITLE
react-native-vector-icons is required ?

### ISSUE THREAD

**Issue by dev4xy** [react-native-training/react-native-elements#1245]
I get this error after use of react-native-elements:

![xxxx](https://user-images.githubusercontent.com/36417203/41052760-f855897e-69ce-11e8-808b-687802476323.png)

**Comment by iRoachie** [comment]
You haven't setup react-native-vector-icons. Follow the instructions [here](https://react-native-training.github.io/react-native-elements/docs/0.19.0/getting_started.html) under 'React Native CLI'

**Comment by dev4xy** [comment]
@iRoachie Thanks. But why it's essential ?!

**Comment by iRoachie** [comment]
It's used for almost all the components.

**Comment by iRoachie** [comment]
It's a lot more components than that, feel free to see all the uses https://github.com/react-native-training/react-native-elements/search?q=Icon&unscoped_q=Icon

**Comment by dev4xy** [comment]
@iRoachie 
Thanks you for answer and good support. ♥

I was reviewing the `0.19.0` version and confused.
And now I saw the `1.0.0-beta5` version that I think is something that was in my mind.

```
import { Button } from 'react-native-elements';
import Icon from 'react-native-vector-icons/FontAwesome';
<Button
  icon={
    <Icon
      name='arrow-right'
      size={15}
      color='white'
    />
  }
  title='BUTTON WITH ICON COMPONENT'
/>
```

Separately imported is good.


For me, the optimality of my program is very important. So I was sensitive to this.
But again, in my opinion, It is better to remove dependencies. (My thought may be wrong.)

Thanks

**Comment by xavier-villelegier** [comment]
@dev4xy 
All our components are designed to work with Icons as easily as possible. As the icons are nowadays an essential part of mobile applications, we decided to make it a core dependency of the project, and, therefore, make the icons usage easy in our components for the beginners. RNE is above all a library that should make the developer life easy by using already made component, and we think that icons are an essential part of these components, and should be easy to use. This means that you shouldn't need to re-implement your own Icon component and use it in all RNE components, RNE should do that for you.

Moreover, `react-native-vector-icons` is the only core dependency we have (except 2 lodash functions), which is, I think, quite acceptable, as the fonts of vector icons are like 1Mo (and for people that are using Expo, the icons are already included)

For these reasons, I'm closing this issue because it's not planned yet to remove `react-native-vector-icons` from the dependencies. Hope you understand our motivations !
