### ISSUE TITLE
How to set ListItem onPress underlayColor in 1.0.0-BETA5?

### ISSUE THREAD

**Issue by AaronBentley** [react-native-training/react-native-elements#1256]
Hello everybody 👋,

First off, thank you for such a nice UI library, its' been a joy to implement React Native Elements into my latest project 🕺

However, I can't figure out how to set the underlay colour for the ListItem component (the background colour when a user taps the list item).
I have found this [reference to underlayColor prop in the 0.19.0 docs](https://react-native-training.github.io/react-native-elements/docs/0.19.0/lists.html#underlaycolor) but nothing more.

`
<ListItem underlayColor={"red"} />
`

Is something like this possible in the latest version?
Thanks in advance,

Aaron.

**Comment by xavier-villelegier** [comment]
Hey @AaronBentley 👋 We're using `TouchableOpacity` for the `1.0.0-beta5` `ListItem`, not `TouchableHighlight` anymore. You can still pass your own component using the `component` props, but you won't be able to use `component={TouchableHighlight}` because TouchableHighlight takes only one child, that implies bit of refactoring on the `ListItem` (cc @martinezguillaume)

**Comment by AaronBentley** [comment]
Apologies for the late reply, life gets in the way sometimes.

@xavier-villelegier Thank you for the informed answer, I'm just pleased I hadn't missed a little detail or config setting.

I think this would be a nice addition in order to maintain consistent UI theming, however the default grey is subtle enough to fit in with most themes.

Keep up the good work and thanks again.

**Comment by martinezguillaume** [comment]
@AaronBentley This [pr](https://github.com/react-native-training/react-native-elements/pull/1233) will fix your problem ! It'll be available in the beta 6
