### ISSUE TITLE
Keep SearchBar Cancel button visible when losing focus.

### ISSUE THREAD

**Issue by mzu** [react-native-training/react-native-elements#1303]
**Is your feature request related to a problem? Please Describe.**
It would be great to have the option to **not** hide the cancel button inside SearchBar-ios.js when the onBlur() event is happening. There are cases when it is useful to cancel the search without having to tap into the text field so that that the button becomes available again. For instance after scrolling through a list of search results.

**Describe the solution you'd like**
Keep the Cancel button visible as long as the search input field is not empty.

**Describe alternatives you've considered**
Forking?

**Comment by iRoachie** [comment]
Sounds like a neat feature.

**Comment by raulgrecio** [comment]
HACK in beta.5 with: inputContainerStyle={{ width: SCREEN_WIDTH - 87.667 - 8 - 8, marginRight: 0 }}

**Comment by renato-bvdash** [comment]
@iRoachie I need this feature kind of badly (boss is asking for it). Do you think this will be available soon?
I saw that other feature thread you guys are making. Seems you are making some good progress 😄

**Comment by iRoachie** [comment]
Yea @renato-bvdash, we're almost done, just a few changes that need to be made. See #1533 for progress

**Comment by Botsy** [comment]
@iRoachie Do you have any updates on this fix? Currently in v1.1.0 on iOS it is not possible to press cancel at all since it hides every time the search input is blurred, which makes calling `onCancel` callback impossible.

Also, there is an issue pressing clear button as well without blurring the search input. Pressing Clear leads to Cancel hiding and nothing happening. I guess fixing the issue with the cancel hiding on blur may help improving the user experience a bit.

I would be very grateful if you could suggest any idea how this could be fixed temporarily before releasing it in any next version.

Thank you

**Comment by iRoachie** [comment]
@Botsy Can you explain what you are trying to accomplish and how you currently doing so? Pressing the clear button does not lead to cancel hiding. You can even see example here https://snack.expo.io/@roach_iam/Y3VyaW.

![kapture 2019-03-04 at 0 19 39](https://user-images.githubusercontent.com/5962998/53710384-50a80480-3e13-11e9-8e8e-5cd008bcac70.gif)

**Comment by Botsy** [comment]
@iRoachie The issue in my case was that the search was inside a ScrollView and I hadn't passed `keyboardShouldPersistTaps="handled"` prop to it, so I had to tap twice for the cancel button to handle the tap. Applying this "fix" did the work for me.

**Comment by dellwatson** [comment]
yes please add this, when i want in focus, i  wanted to add new layout... like instagram search

thats why i dont want onBlur trigger "onCancel" and remove "Cancel button" because my additional layout would be gone too.

I forked and tried to fix the issue

**Comment by iRoachie** [comment]
I’m still having trouble understanding what this feature should be like 😔. Can anyone show visually what this wold look like?

**Comment by dellwatson** [comment]
@iRoachie , might be like this one

![t_video6192987707166163028](https://user-images.githubusercontent.com/13269454/62020786-944e4100-b1ee-11e9-9f39-d025b5695d4d.gif)


1. so when onFocus, the cancel-button beside search bar would appear.

2. if onBlur, the cancel-button wouldnt disappear ( the current version of RN element always dissapear everytime onBlur, this is the issue/ the new feature  )

3. the only way to remove the the cancel-button is by tap again the cancel-button itself, not when onBlur

just like this instgaram, when onFocus, it would change to the 2nd layout screen and the only way to go back to the 1st layout screen only by tap again the cancel button, not in blur-method... because if this func onBlur(blur method) not applied then everytime i scroll/tap on 2nd screen it would go back to the 1st screen layout

i'm currently trying to fix it, but im newbie in contribution ... so it would takes time how to do a proper contribution and to Add this new props, but my speculation is from this code line

`right: hasFocus ? 0 : -this.state.cancelButtonWidth,`

to this by adding new option from new Props for this feature too ?

`
right: hasFocus || this.state.showCancel ? 0 : -this.state.cancelButtonWidth,`

**Comment by joelfsreis** [comment]
+1

**Comment by JimTeva** [comment]
Thank you @iRoachie !!

**Comment by karimdakroury** [comment]
@iRoachie i am trying to implement the same feature, i have a search bar and a flatlist. currently when i press on search bar and start scrolling my flatlist the cancel button is shown but my keyboard is open. i have tried adding

 keyboardShouldPersistTaps='handled'
keyboardDismissMode='on-drag'

to my flatlist, and now when i start scrolling the keyboard disappears but the search bar losses focus and the cancel button disappears.

How do i solve this issue?
