### ISSUE TITLE
Latest documentation doesn't match latest release

### ISSUE THREAD

**Issue by philipwhiuk** [react-native-training/react-native-elements#1460]
## Current State

1. The latest docs deployed are for 1.0.0-beta5
2. The latest release is 1.0.0-beta6
3. The links in the GitHub repository point to the 0.19.0 and the only way to get to 1.0.0-beta5 docs is URL crafting.

## Problems Arising

Difficult to find documentation on `Input` and lack of clarity that `FormValidationMessage` is removed.

## Fixes

1. Change the documentation so it's easier to select the version of docs you want to view
2. Deploy the documentation for 1.0.0-beta6
3. Change the deployment process so this step isn't missed
4. Change the deployment process to update the links in the README.

Other things that could be done:

* Auto-deploy the docs for **master** as well.

**Comment by iRoachie** [comment]
The latest docs are beta 6 and they're already deployed - https://react-native-training.github.io/react-native-elements/docs/getting_started.html.

The deployment process is apart of the CI and happens when we push to master.

0.19.1 is the current stable versions and the other's are betas. So any links in the readme should go correctly to 0.19.1

**Comment by iRoachie** [comment]
We had a small hiccup where we mistakenly published 1.0.0-beta6 as the current stable version and not as a beta. So we had to remove the version. Just fixed the problem now and it'll show beta7 as the latest version and 0.19.1 as the current when you `npm install`
