### ISSUE TITLE
crashing the app on android in expo

### ISSUE THREAD

**Issue by yash2code** [react-native-training/react-native-elements#1549]
I have developed an app which is crashing on android in expo though working on ios.

I am using version 0.19.1

Here is the  [snack](https://snack.expo.io/@yash2code/toffee)

**Comment by iRoachie** [comment]
So i downloaded your snack and ran it. The problem is that you are passing incorrect values to styles. You are doing this in a couple places:

`fontSize` accepts a number, instead you have it assigned a string. Same for flex.
```js
// WRONG
<Text style={{ fontSize: '20' }} />
<View style={{ flex: '1' }} />

// CORRECT
<Text style={{ fontSize: 20 }} />
<View style={{ flex: 1 }} />
```

You also have `height: '1'` which isn't allowed. Height only accepts a string if it's a percentage. Other than that it's a number

```js
// WRONG
<Divider style={{ width: '1%', height: '1', marginTop: '5%' }} />

// CORRECT
<Divider style={{ width: '1%', height: '1%', marginTop: '5%' }} />
<Divider style={{ width: '1%', height: 1, marginTop: '5%' }} />
```

The `borderRadius` prop on the Button is supposed to be a number. See docs https://react-native-training.github.io/react-native-elements/docs/0.19.1/button.html#borderradius.
```js
// WRONG
<Button borderRadius="12" />

// CORRECT
<Button borderRadius={12} />
```

Also there no `display: 'flex'` in react-native.

After making those changes, here's the running app https://snack.expo.io/@roach_iam/toffee
