### ISSUE TITLE
Question: Is it possible to toggle active Theme at runtime?

### ISSUE THREAD

**Issue by kewilson** [react-native-training/react-native-elements#1714]
Hi all,

Wondering if toggling the active theme during run time at a global level is possible? I only want to wrap the entire app and control the theme in use once as the general idea is shown below. 

Thanks for any thoughts, workarounds, suggestions to achieve the objective in advance .. much appreciated!  

Using "react-native-elements": "git+https://github.com/react-native-training/react-native-elements.git#next"

**Is your feature request related to a problem? Please Describe.**

Unable to toggle between predefined light/dark themes at run time.

**Describe the solution you'd like**

Would like the ability to toggle the active theme via user control.

**Describe alternatives you've considered**

Only having a single theme.

**Additional context**

const LIGHT_THEME = { ... }
const DARK_THEME = { ... }

export default class App extends React.Component {
    state = {
        events: filterEvents(moment()),
        isLoadingComplete: false,
        lightTheme: true,
        currentTheme: LIGHT_THEME,
    };

    toggleTheme = () => {
        this.setState({lightTheme: !this.state.lightTheme})
        if (this.state.lightTheme === true){
            this.setState({currentTheme: LIGHT_THEME})
        }else{
            this.setState({currentTheme: DARK_THEME})
        }
    }

    render () {
        return (
            <ThemeProvider theme = {this.state.currentTheme}>
                <Button onPress={() => this.toggleTheme()} />
            </ThemeProvider>
        )
    }
}

**Comment by iRoachie** [comment]
Currently right now this isn't possible. The ThemeProvider doesn't allow runtime changes to it's props. This is because changes to the props of the ThemeProvider will trigger a rerender for all components under the tree.

You can however use the withTheme HOC or ThemeConsumer directly to access the `updateTheme` method. https://react-native-training.github.io/react-native-elements/docs/customization.html#using-the-theme-in-your-own-components

**Comment by kewilson** [comment]
Yeah, I'm sure I just did it wrong but, tried wrapping ThemeConsumer around my ThemeProvider. Also tried fiddling with the updateTheme but again I'm sure I wasn't doing it correctly. Will noodle on those a bit more to see if I can come up with something that'll do the deed, thanks!

**Comment by iRoachie** [comment]
Here's a small example

```jsx
import * as React from 'react';
import { View, StyleSheet } from 'react-native';
import { Constants } from 'expo';

// or any pure javascript modules available in npm
import { Button, withTheme, ThemeProvider } from 'react-native-elements';

const theme = {
  colors: {
    primary: 'red',
  },
};

const AppText = withTheme(({ updateTheme }) => (
  <View style={styles.container}>
    <Button
      title="Hey"
      onPress={() =>
        updateTheme({
          colors: {
            primary: 'pink',
          },
        })
      }
    />
  </View>
));

export default () => (
  <ThemeProvider theme={theme}>
    <AppText />
  </ThemeProvider>
);

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#ecf0f1',
    padding: 8,
  },
});

```

**Comment by msageryd** [comment]
I'm evaluating RNE as the base for the components in my project. Being able to change theme in runtime is a crucial part for my app. If I understand the above answer correctly, this is not possible.

The argument for this is: "This is because changes to the props of the ThemeProvider will trigger a rerender for all components under the tree".

Rerender all components under the tree is exactly what is needed if the theme changes, so I don't understand why this is an argument against such functionality.

I might have misunderstood something. Being able to change theme in runtime is an essential part of a theming system IMO. Isn't there anyway of calling `updateTheme` on the root component and have it trickel down the tree?

**Comment by ebo7** [comment]
The previous react-native-elements/react-native-elements seemed to support this? Did it stop working?
