### ISSUE TITLE
Setting backgroundColor in avatarStyle hides title (Android)

### ISSUE THREAD

**Issue by dimgrav** [react-native-training/react-native-elements#1954]
**Explain what you did**
Apply custom value to `avatarStyle` `backgroundColor` property.

**Expected behaviour**
Change the `backgroundColor` accordingly and do not affect any other styles.

**Describe the bug**
The color changes as expected, but the `Avatar` title disappears (**Android only**).

**To Reproduce**

1. Set a title in an `Avatar` component
2. Set a custom `avatarStyle` property with a user-defined `backgroundColor` value.

**Possible Solution**
Pending investigation.

**Screenshots**

Android
![Android](https://user-images.githubusercontent.com/24510850/61122887-a2405a00-a4ab-11e9-9a12-2e3332bc5646.png)

iOS
![iOS](https://user-images.githubusercontent.com/24510850/61122928-bbe1a180-a4ab-11e9-984b-b66a72bc9dcf.png)

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |     1.1.0    |
| react-native          |    0.59.8     |
| npm or yarn           |    yarn     |

**Comment by iRoachie** [comment]
Use the `overlayContainerStyle` prop for this. `avatarStyle` really only applies for if an image is used.

**Comment by dimgrav** [comment]
@iRoachie will do, but why would iOS render as expected if that's the case?

**Comment by iRoachie** [comment]
This is fixed now on next. `avatarStyle` and `overlayContainerStyle` should behave the same on both platforms now. This was because the Image Component had a different layout on iOS and Android. See (https://github.com/react-native-training/react-native-elements/commit/e2795821fa85bbce48282b9c92d2260658d5c35e#diff-db91516ae3fd33db904a11400a5e19e4)

Will be available in 1.2.0
