### ISSUE TITLE
Export ThemeContext so it can be used with useContext

### ISSUE THREAD

**Issue by bdombro** [react-native-training/react-native-elements#2007]
**Is your feature request related to a problem? Please Describe.**
I use Hooks and Typescript, and wrapping all of my components with withTheme is ugly. 

**Describe the solution you'd like**
It would be nice if we simply exported ThemeContext from ThemeProvider.

**Describe alternatives you've considered**
I'm currently using npm:patch-package to monkey patch this package.

**Comment by bdombro** [comment]
Thanks @iRoachie !

**Comment by braincore** [comment]
I'm using a custom theme `Theme<MyTheme>`. Is there a TypeScript-friendly way of defining `ThemeContext` appropriately? Right now, it's `React.Context<ThemeProps<{}>>`. Ideally, it would be `React.Context<ThemeProps<T>>`.

Guessing it wasn't done this way in your diff since the definition is a const: `const ThemeContext = ...` which I don't think can be parameterized. Any suggestions?

**Comment by braincore** [comment]
For now, I'm getting by with a type assertion:

`const { theme } = useContext(ThemeContext) as ThemeProps<MyTheme>;`
