### ISSUE TITLE
DatePicker Or Calendar?

### ISSUE THREAD

**Issue by yaronlevi** [react-native-training/react-native-elements#214]
Library is top notch. But a Date, Time and calendar are missing. I think they are needed in many apps. Can there be added to the roadmap?

**Comment by Monte9** [comment]
In an effort to streamline all RNE issues such that it is easier to get to solutions faster/ submit a new issue we have decided to close any enhancement/roadmap features as "issues". 

Feel free to use this issue to talk about this feature and ping @binoy14 or me (@monte9) if you feel like you can submit a PR for this. Thanks in advance.

Also you can track the status of this feature and all other roadmap features [here](https://github.com/react-native-community/react-native-elements/issues/195#issuecomment-286213704).

**Comment by yaronlevi** [comment]
Thank you very much!

**Comment by cyclops24** [comment]
Please make this component independent from calendar system and with good i18n support. So users can change for example [Moment](http://momentjs.com/) with [Moment-Jalaali](http://momentjs.com/docs/#/plugins/jalaali/) and use it as a **Persian DatePicker**. Something happend in [MaterialUI datepicker](http://www.material-ui.com/#/components/date-picker) (it's independent from calendar and support many calendar system because use [intl](https://github.com/andyearnshaw/Intl.js) in their component)

**Comment by Monte9** [comment]
We plan to support this soon, but in the meantime please check out this calendar library instead:
https://github.com/wix/react-native-calendars

**Comment by aaymont** [comment]
Is there any progress on this?

**Comment by iRoachie** [comment]
@aaymont Not as yet, feel free to suggest ways in which we could implement. Current in the apps I make I use https://github.com/mmazzarolo/react-native-modal-datetime-picker.

**Comment by dlucidone** [comment]
@iRoachie Not able to trigger action with formInput can you share some code ?

**Comment by Monte9** [comment]
**My suggestion:** If you need a Calendar component in React Native, use Wix's [React Native Calendar](https://github.com/wix/react-native-calendars). 

I personally used it where I work and we had great success with it. It's really well built and is extremely flexible, so even if you need some custom UI.. chances are it can handle it.

Here's what our calendar looks like just as a reference.

<img width="334" alt="screen shot 2018-05-23 at 10 27 44 am" src="https://user-images.githubusercontent.com/7840686/40440859-0a676788-5e74-11e8-912e-a6bbeb928a0d.png">


@iRoachie I'd suggest that instead of reinevnting the wheel, we should just direct people to use [react-native-calendars](https://github.com/wix/react-native-calendars) instead.

**Comment by iRoachie** [comment]
Thanks a good idea! I'll lock this issue for just that.
