### ISSUE TITLE
Multiple ref in input does't work

### ISSUE THREAD

**Issue by anishtr4** [react-native-training/react-native-elements#392]
Using following code I am able to get only the last input ref(password). Not getting the  'username'.

```
  

   <FormLabel>Username</FormLabel>
<FormInput initialValue={usernameValue} onChangeText={(e) => this.updateUserText(e)} ref='forminput' textInputRef='username' />


<FormLabel>Password</FormLabel>
<FormInput initialValue={passwordValue} onChangeText={(e) => this.updatePasswordText(e)} ref='forminput' textInputRef='password'  secureTextEntry={true} />
```

**Comment by MartinCamen** [comment]
How's your code to get the correct form element?

`this.refs.forminput.refs.username` & `this.refs.forminput.refs.password` ?

**Comment by anishtr4** [comment]
Can you correct my code if I am doing wrong ?

**Comment by filiphosko** [comment]
You can't have more than one because it will just overwrite the content of the ref with the last textInputRef. It's a bug (or a flawed implementation). On the other hand, passing strings into refs is deprecated, you can check out [this eslint rule](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-string-refs.md) - the recommended way is to pass in a callback function. If you want to have one 'form container' for your input refs, you can just use a class variable in your component and add your refs to it:

```jsx
class Example extends React.Component {
  form = {}; // container variable

  componentDidMount() {
    console.log(this.form); // you can now access both of your input refs from form
  }

  render() {
    return (
      <View>
        <FormInput
          textInputRef={(c) => { this.form.name = c; }}
          value="Johnny Bravo"
         />
        <FormInput
          textInputRef={(c) => { this.form.email = c; }}
          value="yellowhaireddude@hotmail.com"
        />  
      </View>
    )
  }
}
```

It will warn you about a failed prop type, it's because the FormInput component supports only string type for the textInput prop - so just ignore the warning. We will have to give this component a little polish 💅.

**Comment by Monte9** [comment]
@filiphosko I was aware of the bug but never got around to patching it up. 😢 

Also your explanation about passing in a callback func makes sense. I know you have been contributing a ton to RNE, ;) any chance you could submit a PR for this as you prob know exactly what kind of refactoring it will take?

**Comment by Monte9** [comment]
PR #362 has related discussions about handles multiple refs. 

@filiphosko I am going to defer to you on this. Going forward, how can we refactor such that we are handling multiple refs the right way? 

Also wanna get @Nickman87 thoughts on this.

**Comment by Nickman87** [comment]
Looking at the original question, the issue relies not in RNE but in the double `ref="forminput"` which is not supported by react.
To me, exposing internals trough "refs" (or any other way) is a smell. Adding methods to the component instance and mapping them to the correct components internally seems like the way to go for me.

 @anishtr4 What do you want to use the refs for?

**Comment by filiphosko** [comment]
I think @Nickman87 already refactored it and from the point of backwards compatibility it's cool. What I think we really need now is just changing the docs, since they encourage users to pass strings into refs and get the refs using this.refs https://react-native-training.github.io/react-native-elements/API/forms/ . Also I was thinking about marking textInputRef and containerRef as deprecated in the docs. What do you think? I don't know if it would we wise but now we can use 'ref' on the component itself to get the methods (blur, focus, ...) from the TextInput so technically I don't know if we'll need the textInputRef anymore. Also I don't know what was/is the purpose of having containerRef prop (View ref), what was the intended usage? If we agree on their deprecation, we don't have to remove the functionality entirely, just mark these props as deprecated in the docs and discourage their usage (we can remove them in later). Also we should provide a correct example of using the methods (blur, focus, ...) on the component.

**Comment by Monte9** [comment]
@Nickman87 PR #362 should fix this. This will be release in `v0.16.0`
