### ISSUE TITLE
Multiple buttons: same icons with different color not rendering

### ISSUE THREAD

**Issue by Selman555** [react-native-training/react-native-elements#410]
### Description

Hopefully I'm doing something wrong. But there seems to be a problem with button icons.

I setup a simple `ScrollView` with a couple of buttons.
All the buttons have the same icon with a different color.
Only the first button renders correctly. The following buttons don't have an icon or display a question mark in the correct color.

### Reproduction Steps and Sample Code

You can look at [this basic examen on Snack](https://snack.expo.io/rkY6no8G-).
In Snack, all but the first button display a question mark. On both my devices (physical iOS and Android device) the icon is not displayed at all (not even a question mark).

From package.json:

```
    "dependencies": {
      "react": "16.0.0-alpha.6",
      "react-native": "0.44.2",
      "react-native-elements": "^0.12.2",
      "react-native-vector-icons": "^4.2.0",
    },
```

Am I doing something wrong or is this a bug?

**Comment by Monte9** [comment]
@Selman555 sorry for getting back to you this late. 

You made a very simple mistake.. if you look at the snack demo the reason the icons other than the first icon don't display correctly is because you are passing the wrong prop to it. 

this is what you did > ```icon: 'book-open-variant'```
this is what needs to be done > ```name: 'book-open-variant',```

so the icon name needs to be passes as the `name` props and not the `icon` prop. 

Hope this helps. 😃
