### ISSUE TITLE
SearchBar doesn't show clear icon

### ISSUE THREAD

**Issue by rubycop** [react-native-training/react-native-elements#417]
Code from example doesn't show clear icon
```
import { SearchBar } from 'react-native-elements'

<SearchBar
  onChangeText={someMethod}
  placeholder='Type Here...' />
```
react-native: "0.41.2"

**Comment by Silvercast** [comment]
of course it doesn't. you need to add `clearIcon` props.

```
  onChangeText={someMethod}
  placeholder='Type Here...' />
  clearIcon
```

**Comment by rubycop** [comment]
DOESN'T work with `clearIcon` of course!
```
<SearchBar
          containerStyle = {styles.search}
          inputStyle = {styles.searchInput}
          placeholder = "Search contact"
          placeholderTextColor = "lightgray"
          icon = {{ color: '#86939e', style: styles.searchIcon }}
          clearIcon
          onChangeText = {this._handleSearch}
        />
```

**Comment by binoy14** [comment]
@rubycop I apologize for closing this without providing further explanation. Take a look at the snack https://snack.expo.io/r1tvbm3GW where the Icon is showing up. What versions of react-native-elements are you using? 

P.S: Let's remember to keep a positive environment since we are all trying to help each other.

**Comment by rubycop** [comment]
It doesn't work on:
- android v. 5.0.2
- react-native v. 0.14.2
Seems like it's an android issue
(FYI snack doesn't launch this code on android)

**Comment by martinezguillaume** [comment]
`clearIcon` needs to be an object like this
```js
{
  color: '#86939e',
  name: 'search',
}
```
In your example above, it's just a boolean

**Comment by rubycop** [comment]
@martinezguillaume I'm sorry it was a first raw my example. 
Now I have `icon` and `clearIcon` too
```
<SearchBar
  containerStyle = {styles.search}
  inputStyle = {styles.searchInput}
  placeholder = {I18n.t('search')}
  placeholderTextColor = "lightgray"
  icon = {{ color: '#3B6693', style: styles.searchIcon, name: 'search' }}
  clearIcon = {{ color: '#86939e', name: 'search' }}
  onChangeText = {this._handleSearch.bind(this)}
/>
```
`icon` attr works fine but not `clearIcon`

**Comment by peacechen** [comment]
The [SearchBar documentation](https://react-native-training.github.io/react-native-elements/API/searchbar/) says that the default for clearIcon is `{ color: '#86939e', name: 'search' }`.  It doesn't default to that, it defaults to nothing if omitted.  The default should also be something like close instead of search.  Guessing someone copied that from the icon line.

Additionally, on iOS RN 0.45.1 + RNE 0.15, clicking the clearIcon doesn't clear the text.

**Comment by rubycop** [comment]
@peacechen `clearIcon = {{ color: '#86939e', name: 'clear' }}` doesn't work too

**Comment by peacechen** [comment]
@rubycop This works for me
```clearIcon={{ color: '#999', name: 'close' }}```

**Comment by iRoachie** [comment]
Closing this as it seems to fixed on the `next` branch. 

Example used:
```jsx
<SearchBar
  lightTheme
  clearIcon
  placeholder="Type Here..."
/>
```
![screenshot_1501316977](https://user-images.githubusercontent.com/5962998/28743382-9441a0c0-7416-11e7-9810-e498dd2525c9.png)

If the issue persists after next release, then feel free to reopen

**Comment by rubycop** [comment]
on `v.0.15.0` works
