### ISSUE TITLE
Header Component postion

### ISSUE THREAD

**Issue by nimerfarahty** [react-native-training/react-native-elements#427]
### Description

my code below : with react-native-elements version 0.13
`const Events = StackNavigator({
    events: { screen: screens.Home },
    eventDetails: { screen: screens.EventsDetails }
}, { 
    navigationOptions: {
        header: (
            <Header
                statusBarProps={{ barStyle: 'light-content' }}
                leftComponent={{ icon: 'menu' }}
                centerComponent={{ text: 'MY TITLE' }} 
                rightComponent={{ icon: 'home' }}
                outerContainerStyles={{ backgroundColor: 'rgba(155, 89, 182,1.0)', top: 0 }}
            />
        )
    }
});`
<img width="374" alt="screen shot 2017-06-16 at 1 33 12 am" src="https://user-images.githubusercontent.com/5854259/27204530-6d19fd70-5234-11e7-967c-b1ab1f1a6dcf.png">

my problem is the header sticky on bottom instead of top screen , why ? i have use my own header without any issue !

**Comment by filiphosko** [comment]
@nimerfarahty Hi, thanks for pointing this out. I tested it only standalone, never tried it with react-navigation so this bug never jumped on me. There is a styling that shouldn't be there, I'll post a PR to fix this quickly. In the meantime if you want to use this, you can search for the react-native-elements package in your node_modules, find the Header element (src/header/Header.js) and remove the 'bottom: 0' in the outerContainer styles (line 84). That should fix it. I forgot to remove it when I was prototyping this component.

BTW, I am really interested in the reasons you are using this header with react-navigation (I suppose you are using react-navigation), since it provides it's own header element? We initially developed this element only for standalone purposes (UI mockups), but I'm quite interested in why people would need to use it also in other scenarios.

**Comment by filiphosko** [comment]
I posted a PR to fix this. @binoy14 @Monte9 Could you guys merge it?

**Comment by nimerfarahty** [comment]
thanks for the solution , the reason is just testing reason since i have my own header component also i am a big fan of elements package

**Comment by filiphosko** [comment]
@nimerfarahty This repo is still a work in progress and any contributions are very welcomed, so if you'll have some time and are willing to help, there are a lot of things to do/improve :wink:

**Comment by filiphosko** [comment]
Closing this since a fix has been submitted and will be applied to master in the next release.
