### ISSUE TITLE
Cannot install 

### ISSUE THREAD

**Issue by mobilemaster5** [react-native-training/react-native-elements#436]
`npm WARN react-native-elements@0.13.0 requires a peer of react-native-vector-icons@~4.1.1 but none was installed.`

UNMET PEER DEPENDENCY react-native-vector-icons@4.2.0

I am not sure how can I install the `react-native-elements` in my project.
"react": "16.0.0-alpha.12",
    "react-native": "0.45.1",

Regards !

**Comment by dabit3** [comment]
You need to first install `react-native-vector-icons`, then link the library:

`npm i react-native-vector-icons --save`

`react-native-link`

'npm i react-native-elements --save`

This should do the trick.

**Comment by binoy14** [comment]
@mobilemaster5 hopefully that fixes ur issue. I am closing this but if your still having issues feel free to open it again.

**Comment by elichai** [comment]
I have this issue too, Tired linking and deleting node_modules and installing again.
still get: `npm WARN react-native-elements@0.13.0 requires a peer of react-native-vector-icons@~4.1.1 but none was installed.`
although I have `"react-native-vector-icons": "^4.2.0"` installed. (maybe it's because it's too new?)

**Comment by Monte9** [comment]
@elichai this should be fixed in the upcoming release `v0.14.0`. Keep an eye out for it.
