### ISSUE TITLE
issue when rounded corners of a button.   

### ISSUE THREAD

**Issue by jpca999** [react-native-training/react-native-elements#452]
![image](https://user-images.githubusercontent.com/1026325/27564482-fa5f7024-5aa5-11e7-9742-0046d0f4b31e.png)

Here's the code, 

import React, {
  Component
} from 'react';
import {
  View,
  Text
} from 'react-native';

import { FormLabel, FormInput, Button } from 'react-native-elements'

class UserProfileScreen extends Component {

    static navigationOptions = {
      title: 'My Profile',
    };

  render() {
    return (
      <View>
        <FormLabel >First Name</FormLabel>
        <FormInput/>

        <FormLabel >Last Name</FormLabel>
        <FormInput/>

        <FormLabel >email Address</FormLabel>
        <FormInput/>

        <Button
            large
            backgroundColor="#397af8"
            title='Save'
            borderRadius='10'
        />

      </View>
    );
  }
}

export default UserProfileScreen;

**Comment by filiphosko** [comment]
@jpca999 Hi, from the image you posted I don't know what you mean by "corners have a weird crappy look". I see that corners are rounded and that the button is stacked right under the underline of the input box. The other thing is that you are passing a string instead of a number to the ```borderRadius``` prop which by the way is the reason behind some of those warnings you got there. So please try to fix that issue and/or be more specific about your problem, so we can help you.

**Comment by jpca999** [comment]
@filiphosko   I appreciate your reply. Dont you see the square edges still there outside the rounded corners ?

**Comment by filiphosko** [comment]
@jpca999 I'm sorry but I can't see any square edges there.

**Comment by Monte9** [comment]
@jpca999 I think @filiphosko is right >
```I see that corners are rounded and that the button is stacked right under the underline of the input box.```

Add some `paddingTop` to the button and you'll see what he is talking about.
