### ISSUE TITLE
FormInput sizing ignores parent

### ISSUE THREAD

**Issue by mleduque** [react-native-training/react-native-elements#461]
react-native-elements 0.13

FormInput uses screen width minus 30px (on android) as its own width.
If this component is put inside another component that has its own width, or has a margin, it will overflow its parent.
see https://github.com/react-native-training/react-native-elements/blob/master/src/form/FormInput.js#L72 (android) and https://github.com/react-native-training/react-native-elements/blob/master/src/form/FormInput.js#L76 (ios).

**Comment by EnriqueDev** [comment]
Can be easily solved swapping 
`width: window-30`
for
`width: 100%`

this way the TextInput takes the container width instead of its own.

**Comment by iRoachie** [comment]
Fixed in next version release. If it's still broken on release then feel free to reopen this issue.

**Comment by Monte9** [comment]
@iRoachie appreciate the fix, although it's not a good solution going forward. For one, it breaks the tests. See [here](https://github.com/react-native-training/react-native-elements/commit/45a3fcdb1f955ca4eb71dbdd1e8dd61861b3fe34#diff-39821839c8e2b4b26f5864472349ed83R157) for more info on that.

And two, the width of the input can be controlled using the `inputStyle` prop on the TextInput. Since percentages was introduced in a newer version of RN, it's better to have it be a static width for now and let the user pass the size as needed. 

Also this was fixed on `v1`, @mleduque please check that out if you are interested.

**Comment by mleduque** [comment]
> Also this was fixed on v1, @mleduque please check that out if you are interested.

I don't understand, what's v1 ?

**Comment by iRoachie** [comment]
@Monte9 The test were only broken because it was testing against an older version of react-native. After upgrading to 0.42 the tests work fine. However I'll go back through with the revert

**Comment by iRoachie** [comment]
Reverted in favor of using `inputStyle` prop

**Comment by Morriz** [comment]
Why was this reverted? It is still a valid concern, and asking us to provide a workaround (setting `inputStyle`) is not nice. IMO, as a default, the width should be removed completely so that it will take parent width.

**Comment by iRoachie** [comment]
It’s reverted cause it breaks compatibility with older versions of react native. Percentages were only introduced in RN 0.43. Components don’t magically take up available space, so removing the width doesn’t do what you described

**Comment by cyphire** [comment]
I'm having this issue right now... is there a fix for it?

**Comment by xavier-villelegier** [comment]
@cyphire don't know which version you're using, you should open a new issue with more details

**Comment by c-goettert** [comment]
I could fix this issue by actively unsetting the width of the FormInput: 
`<FormInput inputStyle={{width: undefined}} />`
Hope this helps, although I don't think this is still an issues in the current version.
