### ISSUE TITLE
Header element

### ISSUE THREAD

**Issue by gavindinubilo** [react-native-training/react-native-elements#47]
I'm trying to make a view that has a header at the top, similar to what [react-native-navbar](https://github.com/react-native-community/react-native-navbar) is doing, I understand that it may not be great to copy what they are doing, but it would be great to have a unified style out of the box.

**Comment by Monte9** [comment]
@gavindinubilo that's a good idea. Although in my experience, if you are using any navigation library, NavigationExperimental for instance, the header comes with it as well. 

Were you thinking of using this "unified style" throughout your app that's independent of any sort of navigation? Just trying to understand how useful it would be in general.

**Comment by Monte9** [comment]
Ran into this while prototyping a simple UI for an app. I didn't have any sort of navigation although I needed a header and had to write one myself. I think it could be pretty useful if added as part of RN Elements. Will try to implement this soon.

**Comment by gavindinubilo** [comment]
I ran into it when building a fairly simple app, all I needed was a header for a view, it didn't have any navigation components to it. Though having that option would be great.

**Comment by Carpetfizz** [comment]
This seems pretty essential for ListView based apps. How does the Scene change when a row is tapped?

**Comment by binoy14** [comment]
@Monte9 What are your thoughts on having functionality like http://shoutem.github.io/docs/ui-toolkit/components/navigation-bar There is a wide variety of options available

**Comment by gavindinubilo** [comment]
@binoy14 Something like that would be awesome!

**Comment by Monte9** [comment]
@binoy14 I think that's a great idea. Let me know if you have some time on your hands to start it off.. I can pitch in as well.

**Comment by Monte9** [comment]
In an effort to streamline all RNE issues such that it is easier to get to solutions faster/ submit a new issue we have decided to close any enhancement/roadmap features as "issues". 

Feel free to use this issue to talk about this feature and ping @binoy14 or me (@monte9) if you feel like you can submit a PR for this. Thanks in advance.

Also you can track the status of this feature and all other roadmap features [here](https://github.com/react-native-community/react-native-elements/issues/195#issuecomment-286213704).

**Comment by filiphosko** [comment]
@binoy14 @Monte9 I'm working on this, mostly inspired by NavigationBar (shoutem/ui) and Header (nativebase) components. I could have it done by the end of next week (I hope).

**Comment by binoy14** [comment]
@filiphosko go for it! Let me know if you need any help.

**Comment by filiphosko** [comment]
@binoy14 Sure, I will. Currently I'm analysing another already existing solutions ([NativeBase Header](http://docs.nativebase.io/COMPONENTS.html#Header_Default), [Shoutem UI NavigationBar](https://shoutem.github.io/docs/ui-toolkit/components/navigation-bar), [Community Navbar](https://github.com/react-native-community/react-native-navbar)). They offer different approaches and I would like to discuss later what will be the best solution for this element. I would like to make it as customisable as possible but also avoid unnecessary complexity.

**Comment by Monte9** [comment]
@filiphosko that's great. Thanks for doing it. 

Feel free to post your findings here and we can talk about the implementation details if necessary. @binoy14 and I are actively working on this repo and have some bandwidth. So let us know if you need any help in developing this component so we can ensure that we get this out in a timely manner.

**Comment by filiphosko** [comment]
Sorry for the delay, work stuff got me. Here is some humble 'research' but I'm sure you know all of that already. What is really important for me to know is how would we handle passing in of nav elements and the possibility of 'default layout'.

## Existing solutions

***[React Native Navbar](https://github.com/react-native-community/react-native-navbar)***

It uses 'configuration objects' as props to pass components in:

```jsx
const rightButtonConfig = {
  title: 'Next',
  handler: () => alert('hello!'),
};

const titleConfig = {
  title: 'Hello, world',
};

function ComponentWithNavigationBar() {
  return (
    <View style={styles.container}>
      <NavigationBar
        title={titleConfig}
        rightButton={rightButtonConfig}
      />
    </View>
  );
}
```
It is also possible to pass in a custom component instead of an object.

***[Shoutem UI](https://github.com/shoutem/ui/blob/develop/components/NavigationBar/NavigationBar.js)***

Shoutem NavigationBar uses components as props:

```jsx
<NavigationBar
    leftComponent={<Icon name="face" />}
    centerComponent={<Text>Shoutem UI</Text>}
    rightComponent={<Icon name="home" />}
/>
```

***[NativeBase](https://docs.nativebase.io/COMPONENTS.html#Header_Default)***

Header uses children which are usually wrapped in Left, Right or Body components (but don't have to be):

```jsx
<Header>
    <Left>
      <Icon name="face" />
    </Left>
    <Body>
      <Text>NativeBase</Text>
    </Body>
    <Right>
      <Icon name="home" />
    </Right>
</Header>
```

They are just wrappers with some aligment settings applied:

```javascript
'NativeBase.Left': {
  flex: 1,
  alignSelf: 'center',
  alignItems: 'flex-start',
},
```

---

## Questions

- What style of passing in components would be the best for RN Elements? As props on the parent component (Shoutem UI) or as children (NativeBase)?
- Would it be good/beneficial to support something like 'default layout'? Since most use cases of header/navbar have only 3 elements (left button, title, right button), maybe it would be ok to support some default layout out of the box that could be configured. Configuration options could be passed in as props on the parent element (as it is in React Native Navbar).

---

## My thoughts

- I think the best way is to support passing in children since (at least for me) it is a natural pattern in React that should be supported
- But I also think it would be great to support the default use case only by configuration objects that could be passed in as props, so if somebody would only need the standard layout (two icon buttons and a title) they wouldn't need to create components for them, only to pass title, icon name, onPress handler(s) and maybe some styling to the parent component props for example like this: leftIconBtn={{ name: 'home', onPress: () => console.log('Left button pressed.) }}. Of course the question is that if we will do this default layout stuff with configuration objects maybe it would be good to also allow passing in custom components to props as React Native Navbar does - but maybe also still allow passing in children?

---

What do you think?

**Comment by binoy14** [comment]
@filiphosko I think we should have an API similar to React native navbar since it is similar to how navigation libraries such as react navigation. That is also similar to API in our other components

**Comment by filiphosko** [comment]
@binoy14 Yes, you are right. We could also allow passing nav elements through props like in react navigation (example from their site):

```jsx
class ProfileScreen extends React.Component {
  static navigationOptions = ({ navigation, screenProps }) => ({
    title: navigation.state.params.name + "'s Profile!",
    headerRight: <Button color={screenProps.tintColor} {...} />,
  });
  ...
```

Right now Header only accepts configuration objects for default configuration through props like that. I proposed the default config for people who just need the 'regular' three main elements (left & right buttons and a title) so they can start quickly. But I can also extend that for passing these elements through props, so that way it will create three 'element' groups in which you can put how many elements (buttons, ...) you want.

I would also like to allow passing in children to the component because it just provides the ultimate customisability. React navigation doesn't have this option since they don't expose the header element as is, only it's configuration, but we have a standalone Header that can accept children, so I think we should allow them (in the end there could be three options: 1) default elements with config props, 2) custom element groups with element props, 3) children).

**Comment by filiphosko** [comment]
So I refactored it to support passing in components into props too. I will add tests and push the changes for review.

**Comment by nonameolsson** [comment]
What would be the difference by using React Navigation instead of building a custom component? As I can see, React Navigation has a fully working navigation bar.

**Comment by binoy14** [comment]
@nonameolsson It's if you are not using react-navigation.

**Comment by Monte9** [comment]
Basically, a quick way to mock up the UI without having to necessarily integrate a navigation library into your project just to get a header bar.

**Comment by binoy14** [comment]
This has been merged and will be released in the next release.
