### ISSUE TITLE
Passing empty string as title of <Card /> will throw error

### ISSUE THREAD

**Issue by peteroid** [react-native-training/react-native-elements#516]
To reproduce this error, just put the card element below in your project.

```javascript
<Card title=""></Card>
```

A quick fix would be add a `null` catch to the empty as `title={"" || null}`.

Versions:
- react-native-elements@0.15.0
- react-native@0.45.0

**Comment by Monte9** [comment]
@peteroid this has been fixed on [this commit](https://github.com/react-native-training/react-native-elements/commit/08befcde762c474da736693d8eaead1ed4e3eae8#diff-b593786846659d96a896ce98f3731315). 

It should be out in `v0.16.0` coming out in the next week or so. Feel free to reopen if this is not fixed in the next version.

**Comment by pieter888** [comment]
I had this issue while using 1.1.0.  Tried checking if it was fixed by updating to the latest version (1.2.7) but it was still present.

Passing an empty string to the title prop of a Card causes a crash.
