### ISSUE TITLE
Header is not working

### ISSUE THREAD

**Issue by exos** [react-native-training/react-native-elements#548]
I trying to use Header element and this is not showing.

My code:

```JavaScript
    render() {
        let {title} = this.props;

        return (<Header
          leftComponent={{ icon: 'menu', color: '#fff' }}
          centerComponent={{ text: 'MY TITLE', style: { color: '#fff' } }} 
          rightComponent={{ icon: 'home', color: '#fff' }}
        />);

        // The follow commented code works
        /*
        return (
            <NavigationBar
                title={{
                    title: title,
                    tintColor: "#fff",
                }}
                tintColor="#00ADEE"
                statusBar={{
                    tintColor: "#ff3f80",
                }}
                rightButton={this.resolveRightButton()}
                leftButton={this.renderBackButton()}
            />
        );*/
    }
```
Versions:

* react-native-vector-icons@4.3.0
* react-native-elements@0.15.0

**Edit**: I realized to the Header is showing, (it's are transparent with white text), but It not is showing like a *block* element, getting over the content.

**Comment by Monte9** [comment]
@exos can you please recreate this using [snack](https://snack.expo.io/)? It would be easier to help you debug this issue with a working example. Thanks. 

/cc @filiphosko

**Comment by anarchyrucks** [comment]
@exos You need to set the `backgroundColor` property of `Header` component.

**Comment by filiphosko** [comment]
@exos As @anarchyrucks wrote, your Header items/elements are white and so is the background, nothings shows up that way.

About the positioning 'issue' - the Header has a position: absolute by default, that way it glues it to the top. Normally you would give your content View a margin about the height of the Header and put your content there. But of course it is possible to override the styles (by using the outerContainerStyles prop). Here is the code https://github.com/react-native-training/react-native-elements/blob/master/src/header/Header.js.

**Comment by iRoachie** [comment]
Closing this as inactive. If the problem re-occurs on the latest version of react-native-elements then ping me to reopen. 
Thanks.

**Comment by aloifolia** [comment]
I just stumbled across the same issue. It would be nice of the docs mentioned this "peculiarity" since beginners might not be aware of the fact that you have to

1. keep in mind that the header is positioned absolute and will float above the following content if you forget to add additional margin to the latter,
2. have to add a background color because unlike other libraries like nativebase the header will not have a default bg color.

The documentation is actually misleading - the first example uses a white font color without adapting the background. This seems to be quite... odd. 

Also, what is the default height? Is it the same on every platform or does it vary? For me, it seems to be around 70, but the elements do not seem to be centered vertically (when run in Genymotion on a Google Pixel C device with Android 6.0.0).

**Comment by iRoachie** [comment]
@aloifolia In the next release 0.18. Header will no longer be absolute and require margins or paddings. A default background color seems like something we could add in.
