### ISSUE TITLE
Dropdown Elements

### ISSUE THREAD

**Issue by xstable** [react-native-training/react-native-elements#558]
Would be nice, if you could add those kind of dropdown elements: 
https://www.npmjs.com/package/react-native-modal-dropdown

**Comment by xstable** [comment]
Ok, maybe not such hard needed like I thouht (as react-native-newbe). I've found the <Picker>-Component, which works quite well.
Nevertheless, sometimes it could be usefull to have such dropdowns instead picker

**Comment by iRoachie** [comment]
@xstable It's a great suggestion, and I'd happily accept a pull request that implements it. Dropdowns aren't usually good user experience for a long list of items. 

Image having a dropdown, and screen around it is already in a scroll view.  It encourages nested scroll views in the same direction. Which is usually a bad practice.

Pickers are usually better for user experience because they don't interfere with the current screen

**Comment by Monte9** [comment]
That's a good suggestion @xstable! 👍 

Having a basic dropdown menu could be pretty useful, although I agree with @iRoachie that in such cases it's a better UX to use a picker instead.

In any case, this a duplicate issue for a drop-down menu. #253 Please follow the discussion there.
