### ISSUE TITLE
Header absolute position issue

### ISSUE THREAD

**Issue by ArtixZ** [react-native-training/react-native-elements#584]
### Description

1. Explain what you did
  Use Header from this package.
  Use image as the first component in the page.
2. What you expected to happen
  The image should be under the header.
3. What actually happens
  The image goes under the header, means, the header covers the image.

Also please include the version of `react-native-elements` that you are using.
    0.15.0
### Reproduction Steps and Sample Code

 <View style = {detailContainerSty}>
    <Header
        outerContainerStyles={{ backgroundColor: '#fff' }}
        leftComponent={<Icon 
                            name='chevron-left'
                            type='entypo'
                            color='#43496A'
                            onPress={()=>navigation.goBack()}
                        />}
        centerComponent={{ text: 'Food Profile', style: { fontFamily: 'System', color: '#43496A', 
                                            fontSize: 20 } }} 
    />
    <View style={thumbnailContainerStyle}>
        <Image
            style={thumbnailStyle}
            source={pic}
        />
    </View>
</View>

We highly recommend that you try to reproduce your bug on https://snack.expo.io/ and provide a link.

If you can't reproduce the bug on Snack, provide an example of your code and briefly explain what the code is suppose to be doing.

### Solution
  By overwrting the **outerContainerStyles** style, making postion: relative, I can solve the issue from component level.
Can you suggest a possible fix that would address this issue? Ideally, you should be able to submit a PR to fix it. See our [contributing guide](./CONTRIBUTING.md) for more details.

**Comment by filiphosko** [comment]
@ArtixZ This is not a bug, it's basically how this component works - you have a Header element that has position: absolute and is positioned to the top. So the way you use this API is that you put all your 'main' content into a 'main' view that you indent from the top with `marginTop` by the height of the Header element. Of course it would work with position: relative, but only when you put the Header element as the first element in the stack, basically nothing changes there (the coordinates are 0). I chose position: absolute for the element so it doesn't matter where you put it in the component stack, it will always go to the top.

Of course you can change the API if you'll find that it would be better to not use position: absolute since anyway everybody puts the Header element automatically to the top in their stack.

**Comment by iRoachie** [comment]
Hey @ArtixZ we've had some discussion around this [here](https://github.com/react-native-training/react-native-elements/issues/568#issuecomment-330632279). 

Ideally the header should behave like a normal component on the page and flow with the content instead of being absolutely positioned. This is a great chance for new contributers to get involved :)

**Comment by Misiur** [comment]
Just to be clear, to restore absolute nature of the component, we just have to override `outerContainer` back with absolute positioning?

**Comment by iRoachie** [comment]
Yup, or you can just place it as your first item in the component tree

**Comment by iRoachie** [comment]
Fixed in v18.0.0
