### ISSUE TITLE
Rating flickers in first render

### ISSUE THREAD

**Issue by hendrul** [react-native-training/react-native-elements#755]
In Android and IOS devices I see a flickering when this components renders for the first time, I use StackNavigator from react-navigation to navigate to the screen containing a Rating component, the first time it flickers but then in other screens it doesn't. My current solution is rendering an invisible Rating at some loading screen.
```js
<Rating imageSize={24} style= {{ height: 0, opacity: 0 }}/>
```

**Comment by xavier-villelegier** [comment]
This issue is due to the images used in the `Rating` component. They are loaded and then displayed, and you see that flicker effect when they finished loading and are displayed.

The `Image` component of react native has a `prefetch()` function that allows you to load async images from an url, but the images of the rating component are stored locally, so we can't use this.
I think your solution isn't that bad. But if you're using Expo, I suggest you to [try this](https://docs.expo.io/versions/latest/guides/preloading-and-caching-assets.html), using `require('react-native-elements/src/rating/images/star.png')` (or whatever image you want to load, `star.png`, `heart.png`…)

**Comment by hendrul** [comment]
@xavier-villelegier I already did that and it works for android but in IOS stills flickers, indeed it flickers each time the screen is shown

**Comment by xavier-villelegier** [comment]
If you don't display the `Slider` component as long as the promise is not resolved, it shouldn't flicker.
If it still flickers, try it with your own local images. If you still have this issue I don't think it comes from RNE 😕 But feel free to post the way you're caching your Image, maybe the issue is there.

**Comment by xavier-villelegier** [comment]
Closing this because it has been inactive for 1 month, feel free to reopen it you still have this issue !
