### ISSUE TITLE
Can't change background of Rating

### ISSUE THREAD

**Issue by hendrul** [react-native-training/react-native-elements#756]
I know the implementation uses a rasterized .png image with a transparent hole as a way to apply masking to the animated rectangle that fills the shapes while user interact with the component, I was wondering, and I beg your pardon for my ignorance of CSS3 mechanics, if there is a way to implement this component using vector-icons and CSS3 Masking. Anyway, currently I must use an edited copy of the image with the background of the same color as the container background, but this component can't be used in a translucent container with the current implementation.

**Comment by Monte9** [comment]
Hey @hendrul! Yes, you are right, the current implementation of ratings has several limitations since it uses a custom background in order for the animations to look smooth. 

> if there is a way to implement this component using vector-icons and CSS3 Masking
I am not sure, to be honest. Using svg images, I would think you could possibly implement something similar without the dependency fo having a custom background.

I would suggest you open this issue in the Rating's main repo here: https://github.com/Monte9/react-native-ratings. Hopefully someone there can help out with it, but unfortunately, I don't have enough time at the moment to work on this.
