### ISSUE TITLE
Improve design [DESIGNER NEEDED]

### ISSUE THREAD

**Issue by eduardoinnorway** [react-native-training/react-native-elements#776]
I strongly suggest you get help from a designer. The form and check box examples are for sure not made by a pro designer. They look like made by engineers.

**Comment by Monte9** [comment]
@eduardoinnorway fair point, and you are right. We haven't worked with a designer for RNE. But we sure would like too.

Curious, are you a designer? If so, would you be willing to help out? Or if you know any other really good designer, please send them out way.

**Comment by eduardoinnorway** [comment]
@Monte9 I am not, but I work close to many really good designers, I will ask around if anyone would like to help out in this project.

**Comment by iRoachie** [comment]
Closing as non-actionable. Feel free to add suggestions.

**Comment by Frexuz** [comment]
Can't be that hard. Just mimic a finished design-system made by a real designer.

Here are two nice ones:
http://atomizedesign.com/
https://symboldesign.co/components/

RNE has such good potential. The components are good, but just ugly tbh. I've shown it to multiple developers who are starting out with RN, but are asking me "Why isn't there just a nice looking UI Kit". Nobody has been pleased after I show them RNE :(

**Comment by iRoachie** [comment]
I think it really comes to what you're using it for. They are those with no design experience who just want a UI kit that looks great to build something, and then there's those that already have a design and need components that have the functionality that can be easily customized. 

I think React Native Elements fits somewhere in between.

In my experience, most UI frameworks have a particular look and are very hard to customize. 

However, we'd love to still improve the design all components don't have a consistent feel. Can you point out some components we can tackle and what improvements could be made?

**Comment by Frexuz** [comment]
Ye, I was referring to your point of "They are those with no design experience who just want a UI kit that looks great to build something".

I assume the goal of a UI Kit is to be used by as many devs as possible. Yet many are turned away by their first look, because it isn't good looking.

Agree with your last comment; "However, we'd love to still improve the design all components don't have a consistent feel.". Consistency can be improved.

I'm not in the mood to go into photoshop and annotate some things. But the first things visitors see is this image: https://react-native-training.github.io/react-native-elements/img/app-preview.png
There are definitely too many inconsistencies in that image :)
