### ISSUE TITLE
npm install points to 0.14.0, throwing me "_reactNative.View.propTypes.style is undefined"

### ISSUE THREAD

**Issue by bailih** [react-native-training/react-native-elements#803]
### Description

I use `npm i react-native-elements --save` to install, but somehow I keep getting react native elements @0.14.0.  

The version 0.14.0 keeps giving me "_reactNative.View.propTypes.style is undefined" error when I run the app in production mode.

Here is the installation message:
>`npm i react-native-elements

> react-native-elements@0.14.0 postinstall /....../node_modules/react-native-elements
> opencollective postinstall

>[server error] Cannot load the stats for react-native-elements – please try again later

>npm WARN enzyme-adapter-react-16@1.0.4 requires a peer of react-dom@^16.0.0-0 but none is >installed. You must install peer dependencies yourself.
>npm WARN react-native@0.49.5 requires a peer of react@16.0.0-beta.5 but none is installed. You >must install peer dependencies yourself.
>npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
>npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: >wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

>+ react-native-elements@0.14.0
>updated 1 package in 44.239s
`

### Solution

I finally use the command `npm i --save react-native-elements@0.18.5` to force latest version installation.

**Comment by iRoachie** [comment]
I can't reproduce this error locally @bailih. This is probably 1 of 2 things.

Firstly, try delete your `package-lock.json` if your using npm5. Lock files usually save a particular version of a library so that when reinstalling you will always get the exact version.

Secondly, npm sometimes caches a particular version locally on your computer. You can clear the cache by using `npm cache clean` and then trying the install again.

**Comment by iRoachie** [comment]
Closing as inactive
