### ISSUE TITLE
Beta version throws error `Module does not exists 'expo'`

### ISSUE THREAD

**Issue by deadcoder0904** [react-native-training/react-native-elements#826]
Tried running `react-native init demo && yarn add react-native-elements@beta` & the default application did not work. It throws the following error -

```
Unable to resolve module `expo` from `~/demo`: Module does not exist in the module map
This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
1. Clear watchman watches: `watchman watch-del-all`.
2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
3. Reset Metro Bundler cache: `rm -rf $TMPDIR/react-*` or `npm start -- --reset-cache`.  
4. Remove haste cache: `rm -rf $TMPDIR/haste-map-react-native-packager-*`.
```

It throws error because of [this line in V1 branch](https://github.com/react-native-training/react-native-elements/blob/v1/src/buttons/Button.js#L45) as it uses Expo & I'm not using it.

**Comment by Monte9** [comment]
Ah shit. I knew that would cause a problem. I am going to copy @xavier-villelegier & @martinezguillaume on this. 

What we are trying to do there is to make liner gradient available to the user by using Expo's LinearGradient. But unfortunately `require('expo')` throws an error if not found instead of just returning undefined. 

If you or anyone else has suggestions on how to check if a module/library exists without breaking the app, please let me know.

@deadcoder0904 Let's leave this issue open for a bit, and if we don't find a fix we can get rid of that line and figure out a workaround so `@beta` works with `react native init`

**Comment by deadcoder0904** [comment]
Naah, checkout https://github.com/facebook/react-native/issues/4968 for that issue

**Comment by martinezguillaume** [comment]
Hey ! I can’t see anything related to the issue in your link 😕

What we are trying to do is to detect if the node modules (expo here) exists in your project. @xavier-villelegier runs into a lot of issues, maybe à possible workaround exists now, we have to check

**Comment by deadcoder0904** [comment]
Ohh I thought the error which I've shown has that above link so I thought those 2 might be related.

**Comment by nimo007** [comment]
Any update? I have the same problem

**Comment by Hiro5409** [comment]
+1

**Comment by xavier-villelegier** [comment]
@deadcoder0904 @nimo007 @Hiro5409 
I've tested on a `react-native init` project from scratch, and **yes, it crashes** without passing any `linearGradientProps`.

The dependencies seem to be evaluated anyway, maybe to build the dependency graph or something. I think this is high priority because the `Button` **can not** be used for non-expo users, while this is one of the refactored components that users need to test.

I've commented these lines, to let us time to find a solution (feel free to propose btw). You can use the `next` branch in your `package.json` to use the `Button` in the meantime

```
"react-native-elements": "git://github.com/react-native-training/react-native-elements.git#next"
```

Please tell me if it still doesn't work on the `next` branch 🙏

**Comment by Hiro5409** [comment]
@xavier-villelegier 
Thanks for quick reply! 😄
I really love the feature, LinearGradient button😢 ❤️ 
so anyway, I use expo in the meantime until this issue fix...

I'm looking forward to fix this problem 😃

**Comment by xavier-villelegier** [comment]
@Hiro5409 Yes it seems that `npm i --save expo` allows you to use the `Button` without crashing, but you still can't use the LinearGradient feature. Also, it implies adding a big dependency to your project, which is not what we want our users to.

We'll let you know about updates on this feature

**Comment by hmontes** [comment]
Any progress with this issue? I don't want to install expo and i don't want to address package.json to a github file because i want a version control.

Thank you

**Comment by xavier-villelegier** [comment]
@hmontes This will be in the `v1.0.0-beta2`. In the meantime, you can use these workarounds, or use the last stable release which is `v0.19.0`.

**Comment by hmontes** [comment]
Okey. I'll copy and paste manually the Overlay component because that component isn't in the 0.19.0 version.

Btw. Why don't install linear-gradient package directly? Because that package requires react-native-links? I can help with a pull request or something if you want.

**Comment by xavier-villelegier** [comment]
We want RNE to be available for both vanilla and Expo users. `react-native-vector-icons` requires linking but still works on Expo because `@expo/vector-icons` is based on this package, but this is not the case for `react-native-linear-gradient` apparently, so we're stuck here, as there is no way to require conditionally a package that doesn't exist.

The only solution that we have for now is to allow user to use its own component inside instead of the basic `View` inside the`Button`. Doing this you'll be able to do:

On Expo:
```jsx
<Button
  buttonComponent={require('expo').LinearGradient}
  colors={[GRADIENT_COLORS]}
/>
```

On vanilla rn:
```jsx
<Button
  buttonComponent={require('react-native-linear-gradient').LinearGradient}
  colors={[GRADIENT_COLORS]}
/>
```

But this implies that the linear gradient feature is not really available **inside** RNE Button, but a layer you have to add above.

We're opened to any suggestion about this tho

**Comment by hmontes** [comment]
Perhaps calling a module conditionally.

if you have expo (try require(expo) catch) use @expo/LinearGradient. else use Linear-Gradient package.

You can add the instructions to add https://github.com/react-native-community/react-native-linear-gradient in the installation docs for default installation.

**Comment by xavier-villelegier** [comment]
This doesn't work. As long as you have somewhere `require('expo')`, it will crash if you don't have `expo` module.

You can try by yourself, by doing
```js
if (false)
  require('dummymodule')
```

**Comment by iRoachie** [comment]
Because react native uses haste, it checks for all requires and imports at compile time. So it'll fail long before the code is executed.

**Comment by Ariel-Rodriguez** [comment]
Hi @xavier-villelegier !
Few comments earlier you suggest to use the #next branch as bellow
```
"react-native-elements": "git://github.com/react-native-training/react-native-elements.git#next"
```

Could you publish the <next> branch under "next" tag for NPM? 🙏 
So then it would fetch the package from NPM instead Git
```
"react-native-elements": "next"
```

**Comment by xavier-villelegier** [comment]
@Ariel-Rodriguez This branch is our development branch, so don’t worry it will be released very soon in the beta 2 (Before Monday  probably)

**Comment by Ariel-Rodriguez** [comment]
@xavier-villelegier Thanks for the quick response!

I created a proposal PR, at least it worked on my local but i am concerned about how harmful would be the approach.
I hope you all find it well.

**Comment by xavier-villelegier** [comment]
Okay guys we ended up by doing [this](https://github.com/react-native-training/react-native-elements/pull/857/files). Basically you can still use `linearGradientProps` but you'll need to pass a `ButtonComponent` accordingly to your environment (Expo vs React Native).

The `v1.0.0-beta2` should be released in few hours.

**Comment by xavier-villelegier** [comment]
`v1.0.0-beta2` is now live on npm, have a look at the [release notes](https://github.com/react-native-training/react-native-elements/releases/tag/v1.0.0-beta2) ! There is now a `ViewComponent` props to pass your own LinearGradient component 🔥

**Comment by deadcoder0904** [comment]
Guys I know this has been solved but if you needed to go the way you did it at first, you can do it with https://github.com/satya164/babel-plugin-optional-require
