### ISSUE TITLE
ListItem crash when rightTitle is empty

### ISSUE THREAD

**Issue by MrFoxPro** [react-native-training/react-native-elements#841]
ListItem crashes on android when pass null or empty string to rightTitle

**Comment by LouisJS** [comment]
Could you provide an exemple with https://snack.expo.io/ ?

**Comment by MrFoxPro** [comment]
@LouisJS @xavier-villelegier 
https://snack.expo.io/@foxpro/listitem-crash

**Comment by MrFoxPro** [comment]
Quick fix: replace rightTitle with `<value> || ' '`

**Comment by MrFoxPro** [comment]
![image](https://user-images.githubusercontent.com/17229619/35434899-975d3292-02aa-11e8-8042-81867e779f48.png)

**Comment by xavier-villelegier** [comment]
@LouisJS @MrFoxPro If one of you wants to take the lead on this, have a look at [this comment](https://github.com/facebook/react-native/issues/13243#issuecomment-335488473).

I think just using `!!rightTitle` or `rightTitle !== null` instead of `rightTitle` can do the job [here](https://github.com/react-native-training/react-native-elements/blob/master/src/list/ListItem.js#L191)

**Comment by xavier-villelegier** [comment]
@MrFoxPro Just letting this open until we actually release the fix 👍

**Comment by k3ithl1m** [comment]
I would like to try to fix this

**Comment by xavier-villelegier** [comment]
@k3ithl1m Issues whit the label “Fixed - Next Release” are actually ...*drum roll*... fixed haha

**Comment by k3ithl1m** [comment]
@xavier-villelegier Okay! Haha thanks for informing!

**Comment by xavier-villelegier** [comment]
Fixed in `v1.0.0-beta2`
