### ISSUE TITLE
List aligned at center inside a view

### ISSUE THREAD

**Issue by bianchi** [react-native-training/react-native-elements#846]
I'm trying to put a list inside a view and the list becomes very small if I use alignItems:center in the view.

If I remove alignItems:center it works as expected.
[https://snack.expo.io/B1jVyawHf](url)

**Comment by iRoachie** [comment]
The `List` element itself doesn't have a set width. It uses `flex: 1` to fill the available space. When you use `alignItems` on the surrounding container, then the `List` will only take up enough space to display it's fixed-width children. That's why it's only as big as the room for the icon, and the badge.

You can fix this by giving it a width: `<List containerStyle={{width: 300}}>`

**Comment by bianchi** [comment]
Understood. Thanks for replying
