### ISSUE TITLE
Issue importing 'Input' component 

### ISSUE THREAD

**Issue by repl-ullas-ml** [react-native-training/react-native-elements#855]
### Description

1. Explain what you did
**Trying to use 'Input' element**
2. What you expected to happen
**Should be hassle free experience to import and use it, but ended with the error**
3. What actually happens
**Invariant Violation.Element Type is invalid**

Also please include the version of `react-native-elements` that you are using.
 **"react-native-elements": "0.19.0"**
### Reproduction Steps and Sample Code

https://snack.expo.io/By8z_AqHf

When the module was installed inside **react-native-elements/src/input** folder there was no file input.js, however in https://github.com/react-native-training/react-native-elements the same input.js file is seen under **react-native-elements/src/input** folder.

<img width="354" alt="screen shot 2018-01-25 at 10 08 59 pm" src="https://user-images.githubusercontent.com/11545334/35479245-d611ed42-03af-11e8-8255-e07990866380.png">

**Comment by mlchild** [comment]
I fixed this by using "FormInput" instead of "Input", but not sure if this is recommended

**Comment by xavier-villelegier** [comment]
@repl-ullas-ml You're looking two different versions of RNE. On github the `v1.0.0-beta` is on `master`, but your version is the `v0.19.0`.

On the `v0.19.0`:
• You must import `FormInput`

On the `v1.0.0-beta`:
• The `FormInput` has been refactored and renamed, and is exported as `Input`.

So @mlchild, if you're on `v0.19.0`, you must use `FormInput`, as you did 👍

**Comment by Monte9** [comment]
@repl-ullas-ml you should consider trying out our `v1.0.0-beta` update. We have made a lot of things simpler and much more intuitive to use. Plus things like `Input` have tons of production-ready functionality out of the box.

Checkout this for instance: https://github.com/react-native-training/react-native-elements#rne-ecosystem

As you can see, we already have pre-made login/sign up screens, so you can essentially just copy past the code from our example app and tweak it. Here are some examples for the v1 input component that you can use: https://github.com/react-native-training/react-native-elements-app/tree/master/src/views/login

Hope this helps. And since we are currently on the beta release, please let us know if you have any feedback for the Input component.

**Comment by mkirklions** [comment]
There should be a mention of this in the documentation. This is a legacy problem that is still ongoing until the new version has it.

Does anyone disagree? Am I missing something? 

There was nothing to explain this.

**Comment by iRoachie** [comment]
The website shows the components depending on the version you're viewing at the time.
![screen shot 2018-07-05 at 2 14 12 pm](https://user-images.githubusercontent.com/5962998/42340330-bb79526a-805d-11e8-87d5-5b2a36ce8dc6.png).

All changes are mentioned in the release notes. https://github.com/react-native-training/react-native-elements/releases/tag/v1.0.0-beta. As you can see it's clearly mentioned:

![screen shot 2018-07-05 at 2 17 06 pm](https://user-images.githubusercontent.com/5962998/42340479-1e14277e-805e-11e8-9e1a-dc7297416491.png)

**Comment by mkirklions** [comment]
From the homepage-v19: https://react-native-training.github.io/react-native-elements/

The link on the homepage redirects to beta documentation

https://react-native-training.github.io/react-native-elements/docs/overview.html

A small change to the docs/links can save people hours of checking their own code for the problem.

**Comment by iRoachie** [comment]
Just merged the fix, should be live in a few minutes. Thanks again @mkirklions 💯

**Comment by saaksshi** [comment]
Can anyone tell me whet's the fix ?
