### ISSUE TITLE
Can't change border color of stars in Rating component

### ISSUE THREAD

**Issue by thenewt15** [react-native-training/react-native-elements#863]
Is it possible to change the border color of the stars? The border is always orange, even if I change ratingColor.

Also, while we're here... Is it possible to add margin between each star in this component?

**Comment by LouisJS** [comment]
Hi @thenewt15 ,

The actual Rating system is based on hardcoded Image. So by default, for the stars, you'll have [this frame](https://github.com/react-native-training/react-native-elements/blob/master/src/rating/images/star.png).

There is an option that allows to specify that image you can find on the [demo examples](https://react-native-training.github.io/react-native-elements/API/rating/)

Here it is :

```
const WATER_IMAGE = require('./water.png')

<Rating
  type='custom'
  ratingImage={WATER_IMAGE}
  ratingColor='#3498db'
  ratingBackgroundColor='#c8c7c8'
  ratingCount={10}
  imageSize={30}
  onFinishRating={this.ratingCompleted}
  style={{ paddingVertical: 10 }}
/>
```

I admit that the current Rating implementation isn't the most scalable one, but it still has the merits to exist 😄 .

In order to fix your issue, you could probably take this [image](https://github.com/react-native-training/react-native-elements/blob/master/src/rating/images/star.png), change the color and use it then as a custom image.

**Comment by LouisJS** [comment]
And for the margin, again in the [demo examples](https://react-native-training.github.io/react-native-elements/API/rating/), you'll see that the `Bell` example has margin, while the star doesn't.

I guess it is also related to the image used (The Image for the [Star](https://github.com/react-native-training/react-native-elements/blob/master/src/rating/images/star.png) is different than the [Bell](https://github.com/react-native-training/react-native-elements/blob/master/src/rating/images/bell.png) one ).

If you add some margin in the image itself, that should probably make the trick 🐥

**Comment by Monte9** [comment]
You are right @LouisJS! That's an accurate and detailed explanation of how the images on React Native Ratings works! 👏

**Comment by iRoachie** [comment]
Closing as inactive! If the solution by @LouisJS doesn't work for you, be sure to ping me to reopen the issue.

**Comment by Monte9** [comment]
I think the React Native Rating's src code on this repo is out of sync with the original React Native Rating's library on my repo. 

I think we should consider removing `ratings` src from RNE and just pointing people to use RN Ratings  or possibly through git submodules?

@iRoachie thoughts?

**Comment by Monte9** [comment]
Here' the repo: https://github.com/Monte9/react-native-ratings.

It's starting to get some traction and a few issues. So I might have to start maintaining that as well.

**Comment by iRoachie** [comment]
Definitely think we should move it out. If they want to use the ratings component then w should definitely point them to repo. The other option is to do what we did with Tabs and make it just a shallow wrapper that passes props to the package as a dependency

**Comment by Monte9** [comment]
The ratings does have a white background color.

The source of this is a npm module called `react-native-ratings`. There is a solution posted on the repo here: https://github.com/Monte9/react-native-ratings/issues/26#issuecomment-401279355

**Comment by xavier-villelegier** [comment]
Closing this, please check https://github.com/Monte9/react-native-ratings/issues/26#issuecomment-401279355
