### ISSUE TITLE
SectionList Feature Implementation

### ISSUE THREAD

**Issue by MeKyleH** [react-native-training/react-native-elements#914]
Hi, are there plans to implement a sectionList in react-native-elements? 

It would be really great to be able to divide the lists and have them beautifully styled.

**Comment by xavier-villelegier** [comment]
Hey @MeKyleH ! 👋This is not planned and not a priority for now, since the `SectionList` of react native does the job really well ! Moreover, the `ListItem` can be used pretty easily in a `SectionList`, and the result is quite nice. I advise you to check #777 where I posted [this snack example](https://snack.expo.io/B1pcavgMG), you can see that you can already achieve pretty solid stuff with the `SectionList` 🙌

**Comment by MeKyleH** [comment]
I had to do some finagling to get the data formatted correctly, but the RN SectionList worked great! Thanks for the reference to that good snack!
